server:
  port: 0

spring:
  application:
    name: collector
  cloud:
    config:
      enabled: false

collector:
  kafka:
    topics:
      telemetry-sensors: telemetry.sensors.v1
      telemetry-hubs: telemetry.hubs.v1
    producer-properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: kafka.serializer.GeneralAvroSerializer

grpc:
  server:
    port: 59091

eureka:
  client:
    enabled: false
