server:
  port: 0

spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# Локальные настройки для случаев без Config Server
grpc:
  server:
    port: 59091

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
