spring:
  application:
    name: analyzer
  cloud:
    config:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analyzer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: kafka.deserializer.GeneralAvroDeserializer
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-home
    username: Aleksei
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true

eureka:
  client:
    enabled: false

topic:
  hub-event-topic: telemetry.hubs.v1
  snapshots-topic: telemetry.snapshots.v1